# Generated by Django 6.0.6 on 2026-06-12 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('comptes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('taux_interet_mensuel', models.DecimalField(decimal_places=3, max_digits=5)),
                ('duree_max_mois', models.IntegerField(default=24)),
                ('montant_min', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_max', models.DecimalField(decimal_places=2, default=5000000, max_digits=12)),
                ('garantie_requise', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_demande', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_accorde', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('duree_mois', models.IntegerField()),
                ('taux_interet_mensuel', models.DecimalField(decimal_places=3, max_digits=5)),
                ('objet_credit', models.TextField()),
                ('garantie', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('soumise', 'Soumise'), ('en_etude', 'En étude'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée'), ('decaissee', 'Décaissée'), ('cloturee', 'Clôturée')], default='soumise', max_length=12)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('date_decaissement', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('agent_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits_decides', to=settings.AUTH_USER_MODEL)),
                ('agent_instruction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits_instruits', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_credit', to='clients.client')),
                ('compte_decaissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptes.compte')),
                ('type_credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='credits.typecredit')),
            ],
            options={
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('date_echeance', models.DateField()),
                ('montant_principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_interet', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('en_retard', 'En retard'), ('payee', 'Payée'), ('partiel', 'Partiel')], default='a_venir', max_length=10)),
                ('penalite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='credits.demandecredit')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
