# Generated by Django 6.0.6 on 2026-06-12 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('solde_minimum', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('frais_ouverture', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taux_interet_annuel', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=25, unique=True)),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('bloque', 'Bloqué'), ('cloture', 'Clôturé')], default='actif', max_length=10)),
                ('date_ouverture', models.DateField(auto_now_add=True)),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('agent_ouverture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='clients.client')),
                ('type_compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptes.typecompte')),
            ],
            options={
                'ordering': ['-date_ouverture'],
            },
        ),
    ]
