# Generated by Django 6.0.6 on 2026-06-12 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('comptes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carte31',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('complete', 'Complète — En attente clôture'), ('cloturee', 'Clôturée'), ('annulee', 'Annulée')], default='active', max_length=15)),
                ('montant_case_31', models.DecimalField(blank=True, decimal_places=2, help_text='Montant retenu par la microfinance (dernière case à la clôture)', max_digits=12, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('agent_cloture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartes_cloturees', to=settings.AUTH_USER_MODEL)),
                ('agent_creation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartes_creees', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartes_31', to='clients.client')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartes_31', to='comptes.compte')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CaseDepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_case', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remplie', models.BooleanField(default=True)),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('caissier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='cartes_31.carte31')),
            ],
            options={
                'ordering': ['numero_case'],
                'unique_together': {('carte', 'numero_case')},
            },
        ),
    ]
