# Generated by Django 6.0.6 on 2026-06-12 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartes_31', '0001_initial'),
        ('comptes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresTaxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_operation', models.CharField(choices=[('depot', 'Dépôt'), ('retrait', 'Retrait'), ('transfert', 'Transfert'), ('credit', 'Remboursement crédit'), ('carte_31', 'Carte 31')], max_length=30)),
                ('taux_pourcent', models.DecimalField(decimal_places=3, default=0, help_text='Taux en % (ex: 1.5 pour 1.5%)', max_digits=5)),
                ('montant_fixe', models.DecimalField(decimal_places=2, default=0, help_text='Frais fixe en FCFA', max_digits=10)),
                ('montant_minimum', models.DecimalField(decimal_places=2, default=0, help_text='Frais minimum', max_digits=10)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('depot', 'Dépôt'), ('retrait', 'Retrait'), ('transfert_debit', 'Transfert (débit)'), ('transfert_credit', 'Transfert (crédit)'), ('frais', 'Frais / Taxe'), ('interet', 'Intérêt'), ('remboursement', 'Remboursement crédit'), ('decaissement', 'Décaissement crédit'), ('carte_depot', 'Dépôt Carte 31'), ('carte_cloture', 'Clôture Carte 31')], max_length=25)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('frais', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('solde_avant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('solde_apres', models.DecimalField(decimal_places=2, max_digits=14)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('rejetee', 'Rejetée'), ('annulee', 'Annulée')], default='validee', max_length=12)),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('caissier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_effectuees', to=settings.AUTH_USER_MODEL)),
                ('carte_31', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='cartes_31.carte31')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='comptes.compte')),
                ('compte_lie', models.ForeignKey(blank=True, help_text='Compte destination pour transferts', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_liees', to='comptes.compte')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
