# Generated by Django 6.0.6 on 2026-06-12 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_client', models.CharField(max_length=20, unique=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100)),
                ('type_piece', models.CharField(blank=True, choices=[('cni', 'CNI'), ('passeport', 'Passeport'), ('permis', 'Permis de conduire'), ('autre', 'Autre')], max_length=20)),
                ('numero_piece', models.CharField(blank=True, max_length=50)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('employeur', models.CharField(blank=True, max_length=100)),
                ('revenu_mensuel', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('cloture', 'Clôturé')], default='actif', max_length=10)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('date_adhesion', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('agent_ouverture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_ouverts', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_adhesion'],
            },
        ),
    ]
